draw_set_font(fFine)
draw_set_halign(fa_left)
draw_text(50,100,"For years, the keeper of the forest has watched over Fairlie Forest and the nearby village. ")
draw_text(50,130,"However, recently, many have died of a strange affliction that appears to have come from the forest. ")
draw_text(50,160,"Before you become one of the many who died to this infliction,")
draw_text(50,190,"you decided to prepare to venture into the forest to find out and solve this problem once and for all.")
draw_text(50,220,"However, you haven't come unarmed. You can harvest the energies of the forest and combine them with your blood to")
draw_text(50,250,"create brews, scrolls, and runes to defend yourself from the corrupted beings who reside there.")
draw_text(50,280,"To save the village, you must sacrifice yourself to defeat The Affliction.")
draw_text(50,330,"PRESS ANY KEY OR CLICK TO CONTINUE")